# Generated by Django 5.1.1 on 2024-10-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_articulo', models.CharField(max_length=30, unique=True)),
                ('descripcion_articulo', models.TextField()),
                ('articulo', models.TextField()),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('fecha_agregado',),
            },
        ),
    ]
